version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5005
      # Add CORS-related environment variables
      - CORS_ALLOWED_ORIGINS=https://bookzify.xyz,https://www.bookzify.xyz,https://api.bookzify.xyz
    networks:
      - coolify
      - supabase
    expose:
      - "5005"  # Only expose to other containers, not to host
    labels:
      # Caddy Docker Proxy labels for subdomain
      - "caddy=api.bookzify.xyz"
      - "caddy.reverse_proxy={{upstreams 5005}}"  # Use dynamic service discovery
      - "caddy.reverse_proxy.health_uri=/health"
      - "caddy.reverse_proxy.health_interval=5s"
      - "caddy.reverse_proxy.health_timeout=2s"
      - "caddy.tls.dns=cloudflare"
      # Let the Node.js application handle CORS instead of Caddy
      # This prevents conflicts between Caddy and Express CORS middleware
      # Coolify management labels
      - "coolify.managed=true"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5005/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  coolify:
    external: true
  supabase:
    external:
      name: g00sk4cwgwk0cwkc8kcgc8gk 