version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5005
      # Add CORS-related environment variables
      - CORS_ALLOWED_ORIGINS=https://bookzify.xyz,https://www.bookzify.xyz,https://api.bookzify.xyz
    networks:
      - coolify
      - supabase
    expose:
      - "5005"  # Only expose to other containers, not to host
    labels:
      # Caddy Docker Proxy labels for subdomain
      - "caddy=api.bookzify.xyz"
      - "caddy.reverse_proxy={{upstreams 5005}}"  # Use dynamic service discovery
      - "caddy.reverse_proxy.health_uri=/health"
      - "caddy.reverse_proxy.health_interval=5s"
      - "caddy.reverse_proxy.health_timeout=2s"
      # Removed problematic Cloudflare DNS TLS config - let Caddy use automatic HTTPS
      # Additional debugging and reliability settings
      - "caddy.reverse_proxy.lb_policy=round_robin"
      - "caddy.reverse_proxy.fail_duration=10s"
      - "caddy.reverse_proxy.max_fails=3"
      # Coolify management labels
      - "coolify.managed=true"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:5005/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  coolify:
    external: true
  supabase:
    external:
      name: g00sk4cwgwk0cwkc8kcgc8gk 