version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5005
      # Add CORS-related environment variables
      - CORS_ALLOWED_ORIGINS=https://bookzify.xyz,https://www.bookzify.xyz,https://api.bookzify.xyz
    networks:
      - coolify
      - supabase
    ports:
      - "5005:5005"
    labels:
      # Caddy Docker Proxy labels for subdomain
      - "caddy=api.bookzify.xyz"
      # Use container name for reverse proxy
      - "caddy.reverse_proxy=api:5005"
      - "caddy.tls.dns=cloudflare"
      # Additional Caddy headers for CORS
      - "caddy.header.add=Access-Control-Allow-Origin \"https://bookzify.xyz, https://www.bookzify.xyz, https://api.bookzify.xyz\""
      - "caddy.header.add=Access-Control-Allow-Methods \"GET, POST, PUT, DELETE, OPTIONS, HEAD, PATCH\""
      - "caddy.header.add=Access-Control-Allow-Headers \"Content-Type, Authorization, X-Requested-With, Accept, Origin, Access-Control-Allow-Origin, Access-Control-Allow-Methods, Access-Control-Allow-Headers\""
      - "caddy.header.add=Access-Control-Allow-Credentials \"true\""
      # Coolify management labels
      - "coolify.managed=true"
    # Add container name for stable networking
    container_name: api

networks:
  coolify:
    external: true
  supabase:
    external:
      name: g00sk4cwgwk0cwkc8kcgc8gk 