version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5005
    networks:
      - coolify
      - supabase
    ports:
      - "5005:5005"
    labels:
      # Required for Caddy Docker Proxy discovery
      - "caddy=api.bookzify.xyz"
      - "caddy.reverse_proxy={{upstreams 5005}}"
      - "caddy.tls.dns=cloudflare"
      # Coolify management labels
      - "coolify.managed=true"

networks:
  coolify:
    external: true
  supabase:
    external:
      name: g00sk4cwgwk0cwkc8kcgc8gk 